import type { Item, Lead, FarmerRequest } from "@/types";

export const MOCK_ITEMS: Item[] = [
  // ── LIVESTOCK ──────────────────────────────────────
  {
    id: "1",
    title: "Premium Boran Bull",
    category: "livestock",
    type: "product",
    subcategory: "Cow",
    breed: "Boran",
    age: 3,
    weight: 420,
    price: 85000,
    price_negotiable: true,
    description: "Healthy, well-fed Boran bull. Vaccinated and dewormed. Ideal for beef production or breeding. Has good frame and muscle development.",
    location: "Meru Town, Meru County",
    latitude: 0.047,
    longitude: 37.6496,
    contact_phone: "0712345678",
    status: "available",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    images: [{ id: "i1", item_id: "1", url: "https://images.unsplash.com/photo-1546445317-29f4545e9d53?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
  {
    id: "2",
    title: "Friesian Dairy Cow – 20L/day",
    category: "livestock",
    type: "product",
    subcategory: "Cow",
    breed: "Friesian",
    age: 4,
    weight: 480,
    price: 120000,
    price_negotiable: false,
    description: "High-producing Friesian dairy cow currently milking 20 litres per day. Gentle temperament, easy to handle. Has calved twice. Excellent breeding history.",
    location: "Nkubu, Meru County",
    latitude: 0.0677,
    longitude: 37.7396,
    contact_phone: "0723456789",
    status: "available",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    images: [{ id: "i2", item_id: "2", url: "https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
  {
    id: "3",
    title: "Dorper Sheep Flock – 5 Head",
    category: "livestock",
    type: "product",
    subcategory: "Sheep",
    breed: "Dorper",
    age: 2,
    weight: 55,
    price: 45000,
    price_negotiable: true,
    description: "Five healthy Dorper sheep — 3 ewes and 2 rams. Fast-growing breed, great for meat production. All vaccinated. Can be sold individually or as a flock.",
    location: "Tigania, Meru County",
    latitude: 0.178,
    longitude: 37.907,
    contact_phone: "0734567890",
    status: "available",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    images: [{ id: "i3", item_id: "3", url: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
  {
    id: "4",
    title: "Boer Goats – 3 Head",
    category: "livestock",
    type: "product",
    subcategory: "Goat",
    breed: "Boer",
    age: 1,
    weight: 35,
    price: 18000,
    price_negotiable: true,
    description: "Three healthy Boer goats. Good for meat production. Recently dewormed and vaccinated. Good temperament, easy to manage.",
    location: "Maua, Meru County",
    latitude: 0.231,
    longitude: 37.932,
    contact_phone: "0712345678",
    status: "available",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    images: [{ id: "i4", item_id: "4", url: "https://images.unsplash.com/photo-1590081945069-3e7f58beb4bb?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
  {
    id: "5",
    title: "Kienyeji Chicken – 50 Birds",
    category: "livestock",
    type: "product",
    subcategory: "Poultry",
    breed: "Kienyeji",
    age: 1,
    weight: 2,
    price: 25000,
    price_negotiable: false,
    description: "50 healthy Kienyeji (indigenous) chickens, mix of hens and cocks. Ready for sale or slaughter. Free-range raised on natural feed.",
    location: "Imenti North, Meru",
    latitude: 0.0923,
    longitude: 37.6521,
    contact_phone: "0723456789",
    status: "available",
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    images: [{ id: "i5", item_id: "5", url: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },

  // ── VETERINARY SERVICES ────────────────────────────
  {
    id: "6",
    title: "Dr. James Mutua – Livestock Vet",
    category: "vet",
    type: "service",
    subcategory: "Livestock Vet",
    services_offered: "Vaccination, deworming, disease diagnosis, pregnancy diagnosis, AI services",
    availability: "Mon–Sat 8am–6pm. Mobile visits available.",
    description: "Qualified veterinary surgeon with 10+ years experience in dairy and beef cattle health. Offers mobile vet services across Meru County. Certified by Kenya Veterinary Board.",
    location: "Meru Town, Meru County",
    latitude: 0.047,
    longitude: 37.6496,
    contact_phone: "0745678901",
    status: "available",
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    images: [{ id: "i6", item_id: "6", url: "https://images.unsplash.com/photo-1628348070889-cb656235b4eb?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
  {
    id: "7",
    title: "Meru Animal Clinic",
    category: "vet",
    type: "service",
    subcategory: "General Practice",
    services_offered: "Vaccination, surgery, deworming, disease treatment, hoof trimming, nutritional advice",
    availability: "Mon–Fri 7:30am–5:30pm, Sat 8am–1pm",
    description: "Fully equipped veterinary clinic serving Meru and surrounding areas. Specializes in dairy cattle, small ruminants and poultry. Emergency call-out available.",
    location: "Nkubu Town, Meru County",
    latitude: 0.0677,
    longitude: 37.7396,
    contact_phone: "0756789012",
    status: "available",
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    images: [{ id: "i7", item_id: "7", url: "https://images.unsplash.com/photo-1581093577421-f561a654a353?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
  {
    id: "8",
    title: "Mobile Vaccination Services – Igembe",
    category: "vet",
    type: "service",
    subcategory: "Vaccination",
    services_offered: "FMD, LSD, anthrax, brucellosis vaccination. Farm visits across Igembe sub-county.",
    availability: "Weekdays only. Book 2 days in advance.",
    description: "Affordable mobile vaccination services for livestock farmers in Igembe sub-county. Group bookings welcome — discounts for 20+ animals.",
    location: "Igembe, Meru County",
    latitude: 0.289,
    longitude: 37.951,
    contact_phone: "0767890123",
    status: "available",
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    images: [{ id: "i8", item_id: "8", url: "https://images.unsplash.com/photo-1628348070889-cb656235b4eb?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },

  // ── FEEDS ─────────────────────────────────────────
  {
    id: "9",
    title: "Dairy Meal – 70kg Bag",
    category: "feeds",
    type: "product",
    subcategory: "Dairy Meal",
    feed_type: "Dairy Meal",
    quantity_available: "200 bags in stock",
    price: 3200,
    price_negotiable: false,
    description: "High-quality dairy meal, 18% protein content. Ideal for lactating dairy cows. Formulated to boost milk production. Bulk discounts available for orders of 10+ bags.",
    location: "Meru Town, Meru County",
    latitude: 0.047,
    longitude: 37.6496,
    contact_phone: "0712345678",
    status: "available",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    images: [{ id: "i9", item_id: "9", url: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
  {
    id: "10",
    title: "Layers Mash – Chick & Growers",
    category: "feeds",
    type: "product",
    subcategory: "Poultry Feed",
    feed_type: "Poultry Feed",
    quantity_available: "150 bags in stock",
    price: 2800,
    price_negotiable: true,
    description: "Premium layers mash for chicks, growers and laying hens. 16% protein. Promotes fast growth and high egg production. Delivery available within Meru County.",
    location: "Nkubu, Meru County",
    latitude: 0.0677,
    longitude: 37.7396,
    contact_phone: "0723456789",
    status: "available",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    images: [{ id: "i10", item_id: "10", url: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
  {
    id: "11",
    title: "Rhodes Grass Hay Bales",
    category: "feeds",
    type: "product",
    subcategory: "Hay & Silage",
    feed_type: "Hay",
    quantity_available: "500 bales in stock",
    price: 350,
    price_negotiable: false,
    description: "Dry Rhodes grass hay bales. Well-cured, free from mold. Ideal for dairy cattle and small ruminants. Each bale weighs approximately 15kg. Farm pickup or delivery available.",
    location: "Laare, Meru County",
    latitude: 0.1521,
    longitude: 37.8234,
    contact_phone: "0734567890",
    status: "available",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    images: [{ id: "i11", item_id: "11", url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
  {
    id: "12",
    title: "Goat & Sheep Mineral Lick",
    category: "feeds",
    type: "product",
    subcategory: "Mineral Supplements",
    feed_type: "Mineral Supplement",
    quantity_available: "80 units",
    price: 450,
    price_negotiable: false,
    description: "Mineral salt lick specifically formulated for goats and sheep. Prevents deficiency diseases, improves growth and fertility. Each block weighs 3kg.",
    location: "Meru Town, Meru County",
    latitude: 0.047,
    longitude: 37.6496,
    contact_phone: "0745678901",
    status: "available",
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    images: [{ id: "i12", item_id: "12", url: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },

  // ── PRODUCTS ──────────────────────────────────────
  {
    id: "13",
    title: "Fresh Farm Milk – Daily Supply",
    category: "products",
    type: "product",
    subcategory: "Milk",
    product_type: "Dairy",
    unit: "Per litre",
    price: 55,
    price_negotiable: false,
    description: "Fresh raw milk from Friesian cows. Available daily in the morning. Minimum order 10 litres. Regular supply contracts available for hotels, schools and businesses.",
    location: "Meru Town, Meru County",
    latitude: 0.047,
    longitude: 37.6496,
    contact_phone: "0712345678",
    status: "available",
    created_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    images: [{ id: "i13", item_id: "13", url: "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
  {
    id: "14",
    title: "Farm Fresh Eggs – Trays",
    category: "products",
    type: "product",
    subcategory: "Eggs",
    product_type: "Poultry",
    unit: "Per tray (30 eggs)",
    price: 420,
    price_negotiable: true,
    description: "Fresh free-range eggs from Kienyeji and improved layer chickens. Available in trays of 30. Order by 6am for same-day delivery within Meru Town.",
    location: "Imenti North, Meru",
    latitude: 0.0923,
    longitude: 37.6521,
    contact_phone: "0723456789",
    status: "available",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    images: [{ id: "i14", item_id: "14", url: "https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
  {
    id: "15",
    title: "Organic Cattle Manure – Bulk",
    category: "products",
    type: "product",
    subcategory: "Manure",
    product_type: "Organic",
    unit: "Per tonne",
    price: 1500,
    price_negotiable: true,
    description: "Well-composted cattle manure, excellent for farms and gardens. Rich in nutrients, improves soil structure. Available in bulk. Delivery available for large orders.",
    location: "Tigania, Meru County",
    latitude: 0.178,
    longitude: 37.907,
    contact_phone: "0734567890",
    status: "available",
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    images: [{ id: "i15", item_id: "15", url: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
  {
    id: "16",
    title: "Raw Cattle Hides",
    category: "products",
    type: "product",
    subcategory: "Hides & Skins",
    product_type: "Hide",
    unit: "Per piece",
    price: 800,
    price_negotiable: true,
    description: "Fresh raw cattle hides available in bulk. Suitable for tanneries and leather works. Average size 40–60 sq ft per hide. Consistent supply guaranteed.",
    location: "Maua, Meru County",
    latitude: 0.231,
    longitude: 37.932,
    contact_phone: "0756789012",
    status: "available",
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    images: [{ id: "i16", item_id: "16", url: "https://images.unsplash.com/photo-1560114928-40f1f1eb26a0?w=800&auto=format&fit=crop", created_at: new Date().toISOString() }],
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: "l1",
    name: "John Mwangi",
    phone: "0712111222",
    item_id: "1",
    message: "I'd like to buy the Boran bull. Is it still available?",
    created_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    item: { title: "Premium Boran Bull", category: "livestock" },
  },
  {
    id: "l2",
    name: "Mary Kamau",
    phone: "0723222333",
    item_id: "2",
    message: "Interested in the Friesian cow. Can I visit tomorrow?",
    created_at: new Date(Date.now() - 5 * 3600000).toISOString(),
    item: { title: "Friesian Dairy Cow", category: "livestock" },
  },
  {
    id: "l3",
    name: "Peter Njiru",
    phone: "0734333444",
    item_id: "9",
    message: "Do you deliver the dairy meal to Nkubu? I need 20 bags.",
    created_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    item: { title: "Dairy Meal – 70kg Bag", category: "feeds" },
  },
];

export const MOCK_REQUESTS: FarmerRequest[] = [
  {
    id: "r1",
    name: "Samuel Kiiru",
    phone: "0745444555",
    category: "livestock",
    request_text: "Looking for a pregnant Friesian heifer ready to calve in the next 2 months. Budget KES 90,000.",
    status: "pending",
    created_at: new Date(Date.now() - 3 * 3600000).toISOString(),
  },
  {
    id: "r2",
    name: "Grace Wanjiru",
    phone: "0756555666",
    category: "feeds",
    request_text: "Need a reliable monthly supplier for 50 bags of dairy meal. Located in Timau.",
    status: "pending",
    created_at: new Date(Date.now() - 12 * 3600000).toISOString(),
  },
  {
    id: "r3",
    name: "David Murithi",
    phone: "0767666777",
    category: "vet",
    request_text: "Need a vet for regular AI services and pregnancy diagnosis for my herd of 15 Friesian cows.",
    status: "responded",
    created_at: new Date(Date.now() - 24 * 3600000).toISOString(),
  },
];
